version: '3.9'

services:
  python-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - mysql-db
    volumes:
      - ./app:/app

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user      
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/    

volumes:
  mysql-data: